name: CI

# Trigger the workflow on push or pull request or manually
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

# the `concurrency` settings ensure that not too many CI jobs run in parallel
concurrency:
  # group by workflow and ref; the last slightly strange component ensures that for pull
  # requests, we limit to 1 concurrent job, but for the master branch we don't
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref != 'refs/heads/master' || github.run_number }}
  # Cancel intermediate builds, but only if it is a pull request build.
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  # The CI test job
  test:
    name: "${{ matrix.os }}: GAP ${{ matrix.gap-branch }} ${{ matrix.ABI }}"
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        gap-branch:
          - master
          - stable-4.15
          - stable-4.14
          - stable-4.13
          - stable-4.12
        ABI: ['']
        os:
          - ubuntu
        include:
          - gap-branch: master
            ABI: 32
            os: ubuntu
          - gap-branch: master
            os: windows

    steps:
      - uses: actions/checkout@v5
      - uses: gap-actions/setup-cygwin@v2
        if: ${{ runner.os == 'Windows' }}
      - uses: gap-actions/setup-gap@v2
        with:
          GAPBRANCH: ${{ matrix.gap-branch }}
          ABI: ${{ matrix.ABI }}
      - uses: gap-actions/build-pkg@v2
      - uses: gap-actions/run-pkg-tests@v4
      - uses: gap-actions/run-pkg-tests@v4
        if: ${{ runner.os != 'Windows' }}
        with:
          mode: 'onlyneeded'
      - uses: gap-actions/process-coverage@v2
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
