name: Build manual

# Trigger the workflow on push or pull request or manually
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  manual:
    name: Build manual
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: gap-actions/setup-gap@v3
      - uses: gap-actions/build-pkg-docs@v2
        with:
          use-latex: 'true'
      - name: 'Upload documentation'
        uses: actions/upload-artifact@v4
        with:
          name: manual
          path: ./doc/manual.pdf
          if-no-files-found: error
